# Generated by Django 6.1.1 on 2026-10-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0004_order_confirmed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed_at',
        ),
    ]
